package com.luqta.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 int P=Color.rgb(245,22,166),C=Color.rgb(29,205,255),G=Color.rgb(255,190,70),BG=Color.rgb(5,7,12),CARD=Color.rgb(18,21,28),MUT=Color.rgb(145,150,164); LinearLayout body; ArrayList<String> fav=new ArrayList<>();
 GradientDrawable box(int color,float r){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(r);return d;} GradientDrawable edge(int color,int stroke,float r){GradientDrawable d=box(color,r);d.setStroke(2,stroke);return d;}
 TextView tx(String s,int z,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(14,10,14,10);v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);if(b)v.setTypeface(null,1);return v;}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);splash();}
 void splash(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setBackgroundColor(BG);TextView icon=tx("⌜  ◉  ⌝",62,true);icon.setTextColor(P);icon.setGravity(Gravity.CENTER);r.addView(icon);TextView l=tx("لُقطة",45,true);l.setGravity(Gravity.CENTER);r.addView(l);TextView en=tx("L U Q T A",16,true);en.setTextColor(Color.LTGRAY);en.setGravity(Gravity.CENTER);r.addView(en);TextView tag=tx("شوفها .. نلقطها لك",20,false);tag.setGravity(Gravity.CENTER);tag.setTextColor(Color.LTGRAY);r.addView(tag);setContentView(r);new Handler().postDelayed(this::home,900);}
 void shell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.setBackgroundColor(BG);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(18,14,18,14);sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));root.addView(nav());setContentView(root);}
 View brand(){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView bell=tx("♢",24,false);bell.setGravity(Gravity.CENTER);h.addView(bell,new LinearLayout.LayoutParams(55,55));TextView b=tx("لُقطة\nL U Q T A",24,true);b.setGravity(Gravity.CENTER);h.addView(b,new LinearLayout.LayoutParams(0,70,1));TextView mark=tx("⌜◉⌝",28,true);mark.setTextColor(P);mark.setGravity(Gravity.CENTER);h.addView(mark,new LinearLayout.LayoutParams(70,55));return h;}
 void home(){shell();body.addView(brand());TextView hero=tx("شُفت شيء أعجبك؟\nصوّره ونلقطه لك",27,true);hero.setGravity(Gravity.CENTER);hero.setBackground(edge(Color.rgb(14,15,23),P,34));body.addView(hero,new LinearLayout.LayoutParams(-1,150));TextView camera=tx("▣   ابحث بالصورة",18,true);camera.setGravity(Gravity.CENTER);camera.setBackground(edge(Color.rgb(91,23,112),C,50));camera.setOnClickListener(v->camera());LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,65);cp.setMargins(0,-32,0,15);body.addView(camera,cp);
 EditText q=new EditText(this);q.setHint("ابحث عن أي منتج...");q.setHintTextColor(MUT);q.setTextColor(Color.WHITE);q.setTextSize(16);q.setSingleLine();q.setPadding(20,0,20,0);q.setBackground(box(CARD,35));q.setImeOptions(EditorInfo.IME_ACTION_SEARCH);q.setOnEditorActionListener((v,a,e)->{results(q.getText().toString().isEmpty()?"أفضل اللقطات":q.getText().toString());return true;});body.addView(q,new LinearLayout.LayoutParams(-1,62));body.addView(tx("تسوّق حسب القسم",19,true));String[] c={"♙\nالأزياء","▣\nالمنزل","▤\nالإلكترونيات","◈\nالجمال","⌚\nالإكسسوارات","•••\nالمزيد"};for(int i=0;i<c.length;i+=3){LinearLayout row=new LinearLayout(this);for(int j=i;j<i+3;j++){TextView x=tx(c[j],14,true);x.setGravity(Gravity.CENTER);x.setBackground(edge(CARD,j%2==0?P:C,24));x.setOnClickListener(v->results(((TextView)v).getText().toString().replace("\n"," ")));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,100,1);p.setMargins(4,4,4,4);row.addView(x,p);}body.addView(row);}body.addView(tx("مختارات لُقطة",19,true));productStrip();}
 void productStrip(){LinearLayout row=new LinearLayout(this);String[] n={"كرسي عصري","ساعة فاخرة"};String[] pr={"1,250 ر.س","2,980 ر.س"};for(int i=0;i<2;i++){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackground(box(CARD,26));TextView im=tx(i==0?"▰\nصورة كرسي":"◉\nصورة ساعة",22,true);im.setGravity(Gravity.CENTER);im.setTextColor(i==0?G:C);c.addView(im,new LinearLayout.LayoutParams(-1,120));c.addView(tx(n[i],15,true));TextView p=tx(pr[i],16,true);p.setTextColor(P);c.addView(p);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,205,1);lp.setMargins(5,5,5,5);row.addView(c,lp);}body.addView(row);}
 void camera(){shell();TextView top=tx("×                         ⚡",24,true);body.addView(top);TextView t=tx("التقط صورة للمنتج",24,true);t.setGravity(Gravity.CENTER);body.addView(t);TextView s=tx("أو اختر صورة من المعرض",14,false);s.setTextColor(Color.LTGRAY);s.setGravity(Gravity.CENTER);body.addView(s);TextView f=tx("⌜                                      ⌝\n\n\n\n        وجّه الكاميرا للمنتج\n\n\n\n⌞                                      ⌟",18,true);f.setGravity(Gravity.CENTER);f.setBackground(edge(Color.rgb(12,13,18),Color.WHITE,28));body.addView(f,new LinearLayout.LayoutParams(-1,430));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER);TextView gal=tx("▣\nمعرض",13,false);gal.setGravity(Gravity.CENTER);TextView snap=tx("●",68,true);snap.setTextColor(P);snap.setGravity(Gravity.CENTER);snap.setOnClickListener(v->results("بحث بالصورة"));TextView flip=tx("↻",28,false);flip.setGravity(Gravity.CENTER);bar.addView(gal,new LinearLayout.LayoutParams(0,80,1));bar.addView(snap,new LinearLayout.LayoutParams(0,90,1));bar.addView(flip,new LinearLayout.LayoutParams(0,80,1));body.addView(bar);}
 void results(String q){shell();body.addView(brand());body.addView(tx("نتائج البحث",24,true));TextView search=tx("⌕   "+q,15,false);search.setBackground(box(CARD,30));body.addView(search,new LinearLayout.LayoutParams(-1,55));LinearLayout chips=new LinearLayout(this);for(String z:new String[]{"الكل","أثاث","منزل","متاجر"}){TextView x=tx(z,13,true);x.setGravity(Gravity.CENTER);x.setBackground(edge(CARD,z.equals("الكل")?P:Color.DKGRAY,30));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,45,1);p.setMargins(3,8,3,8);chips.addView(x,p);}body.addView(chips);String[] n={"كرسي مودرن فاخر","كرسي بذراعين عصري","كرسي مخمل أنيق","كرسي عصري مريح"};String[] pr={"1,480 ر.س","1,250 ر.س","1,350 ر.س","1,290 ر.س"};for(int i=0;i<4;i+=2){LinearLayout row=new LinearLayout(this);for(int j=i;j<i+2;j++){final String nm=n[j];LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackground(box(CARD,24));TextView im=tx("♡\n\n▰\nصورة المنتج",17,true);im.setGravity(Gravity.CENTER);im.setTextColor(G);im.setOnClickListener(v->detail(nm,pv));c.addView(im,new LinearLayout.LayoutParams(-1,145));c.addView(tx(nm,15,true));TextView price=tx(pr[j],16,true);price.setTextColor(Color.WHITE);c.addView(price);TextView st=tx(j%2==0?"Home Centre  ★4.8":"IKEA  ★4.6",12,false);st.setTextColor(Color.LTGRAY);c.addView(st);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,255,1);p.setMargins(5,5,5,5);row.addView(c,p);}body.addView(row);}}
 void detail(String n,String p){shell();TextView im=tx("‹                                      ♥\n\n\n▰\n\nصورة المنتج\n\n",24,true);im.setTextColor(G);im.setGravity(Gravity.CENTER);im.setBackground(box(Color.rgb(28,25,21),28));body.addView(im,new LinearLayout.LayoutParams(-1,360));body.addView(tx(n,22,true));TextView price=tx(p,22,true);price.setTextColor(Color.WHITE);body.addView(price);body.addView(tx("Home Centre     ★ 4.8 (124)",14,false));TextView buy=tx("عرض المنتج   ↗",17,true);buy.setGravity(Gravity.CENTER);buy.setBackground(edge(Color.rgb(102,21,116),P,28));body.addView(buy,new LinearLayout.LayoutParams(-1,62));for(String x:new String[]{"تفاصيل المنتج     ‹","خيارات أخرى     ‹","منتجات مشابهة     ‹"}){TextView v=tx(x,15,false);v.setBackground(box(CARD,20));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,58);lp.setMargins(0,5,0,5);body.addView(v,lp);}}
 void favorites(){shell();body.addView(brand());body.addView(tx("المفضلة",24,true));String[] a={"كرسي بذراعين عصري     1,250 ر.س","ساعة يد فاخرة          2,980 ر.س","حقيبة كتف أنيقة        1,450 ر.س","سماعات لاسلكية          690 ر.س"};for(String s:a){TextView v=tx("♥   "+s,15,true);v.setBackground(box(CARD,22));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,78);p.setMargins(0,5,0,5);body.addView(v,p);}}
 void hunt(){shell();body.addView(brand());TextView icon=tx("♧",48,true);icon.setTextColor(P);icon.setGravity(Gravity.CENTER);body.addView(icon);TextView title=tx("صِدها لي",27,true);title.setGravity(Gravity.CENTER);body.addView(title);TextView sub=tx("ما لقيت اللي تبيه؟\nنصيد لك أفضل الخيارات وأفضل الأسعار",16,false);sub.setGravity(Gravity.CENTER);sub.setTextColor(Color.LTGRAY);body.addView(sub);EditText d=new EditText(this);d.setHint("مثال: كرسي مثل الصورة بلون مختلف");d.setHintTextColor(MUT);d.setTextColor(Color.WHITE);d.setPadding(18,0,18,0);d.setBackground(edge(CARD,Color.DKGRAY,24));body.addView(d,new LinearLayout.LayoutParams(-1,75));TextView add=tx("▣   إرفاق صورة (اختياري)",15,false);add.setGravity(Gravity.CENTER);add.setBackground(edge(CARD,Color.DKGRAY,24));body.addView(add,new LinearLayout.LayoutParams(-1,65));TextView send=tx("أرسل الطلب   ➤",17,true);send.setGravity(Gravity.CENTER);send.setBackground(edge(Color.rgb(99,20,114),C,28));body.addView(send,new LinearLayout.LayoutParams(-1,65));}
 void account(){shell();body.addView(brand());body.addView(tx("حسابي",24,true));TextView avatar=tx("TS     Turki SehIi",19,true);avatar.setBackground(box(CARD,28));body.addView(avatar,new LinearLayout.LayoutParams(-1,90));for(String s:new String[]{"▣  طلباتي        ‹","♡  مفضلاتي       ‹","♧  صِدها لي       ‹","⚙  الإعدادات      ‹","?  المساعدة       ‹","○  عن لُقطة       ‹"}){TextView v=tx(s,16,false);v.setBackground(box(CARD,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,60);p.setMargins(0,4,0,4);body.addView(v,p);}}
 View nav(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setBackgroundColor(Color.rgb(10,12,17));String[] a={"⌂\nالرئيسية","♡\nالمفضلة","▣\nالكاميرا","♧\nصِدها لي","○\nحسابي"};for(String s:a){TextView v=tx(s,12,false);v.setGravity(Gravity.CENTER);if(s.contains("الكاميرا"))v.setTextColor(P);v.setOnClickListener(x->{String z=((TextView)x).getText().toString();if(z.contains("الرئيسية"))home();else if(z.contains("المفضلة"))favorites();else if(z.contains("الكاميرا"))camera();else if(z.contains("صِدها"))hunt();else account();});n.addView(v,new LinearLayout.LayoutParams(0,72,1));}return n;}
}
